@startuml L1-PV-UC02

title Level 1 - Create Test Plan

hide empty members

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Developer as D

participant "System" as System
participant "<<External>>\nDatabase" as DB

activate D
D -> System: Requests to create a new Test Plan
activate System
System -> DB: Asks to save Test Plan
activate DB
DB --> DB: Saves Test Plan
DB --> System: Returns saved Test Plan ID
deactivate DB
System -> DB: Asks to find latest Test Plan Version by Test Plan ID
activate DB
DB --> DB: Finds latest Test Plan Version ID
DB --> System: Returns latest Test Plan Version ID
deactivate DB
System -> DB: Asks to save Test Plan Version
activate DB
DB --> DB: Saves Test Plan Version
DB --> System: Returns saved Test Plan Version ID
deactivate DB
System --> D: Confirms creation of Test Plan
deactivate System

@enduml