@startuml use-case-diagram
left to right direction

actor "Developer or CI/CD Pipeline" as Dev

rectangle "Melmac Performance Testing Framework" {
    usecase "UC1: As a Developer, I want to create a Test Suite" as UC1
    usecase "UC2: As a Developer, I want to create a Test Plan" as UC2
    usecase "UC3: As a Developer, I want to run a Test Suite" as UC3
    usecase "UC4: As a Developer, I want to run a Test Plan" as UC4
}

Dev --> UC1
Dev --> UC2
Dev --> UC3
Dev --> UC4

@enduml
