@startuml use-case-diagram
left to right direction

actor "Developer" as Dev

rectangle "Melmac Performance Testing Framework" {
    usecase "Create a Test Suite" as UC1
    usecase "Create a Test Plan" as UC2
    usecase "Run a Test Suite" as UC3
    usecase "Run a Test Plan" as UC4
}

Dev --> UC1
Dev --> UC2
Dev --> UC3
Dev --> UC4

@enduml
