@startuml L1-PV-UC03

title Level 1 - Run Test Suite

hide empty members

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Developer as D

participant "System" as System

activate D
D -> System: Request to run Test Suite
activate System
System -> D: Test Suite Execution Completed
deactivate System
deactivate D

@enduml